config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :importers
  resources :contacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, format: { with: /\A([a-z\d\s\/-]*)\z/i }
  validates :date_of_birth, presence: true, format: { with: /\A[0-9][0-9][0-9][0-9]-((0[1-9])|(1[0-2]))-([0-2][1-9]|3[0-1])\z/i }
  validates :address, presence: true
  validates :phone, presence: true, format: { with: /\A(\(\+[0-9][0-9]\))\s(\d{3})(-|\s)(\d{3})(-|\s)(\d{2})(-|\s)(\d{2})\z/i }
  validates :credit_card, presence: true

  encrypts :credit_card

  validate :credit_card_validation

  before_save :populate_franchise

  private

  def credit_card_validation
    errors.add(:credit_card, :invalid) unless credit_card.creditcard?
  end

  def populate_franchise
    self.franchise = credit_card.creditcard_type
  end
end


# credit_card.split(//).last(4).join

app/models/importer.rb
require 'csv'

class Importer < ApplicationRecord
  has_many_attached :files

  def create_contacts
    path = path = ActiveStorage::Blob.service.send(:path_for, files.first.key)

    CSV.foreach path, headers: true do |row|
      Contact.create!(row.to_hash)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :date_of_birth, :phone, :address, :credit_card, :franchise, :email)
    end
end

app/controllers/importers_controller.rb
class ImportersController < ApplicationController
  before_action :set_importer, only: %i[ show edit update destroy ]

  # GET /importers or /importers.json
  def index
    @importers = Importer.all
  end

  # GET /importers/1 or /importers/1.json
  def show
  end

  # GET /importers/new
  def new
    @importer = Importer.new
  end

  # GET /importers/1/edit
  def edit
  end

  # POST /importers or /importers.json
  def create
    @importer = Importer.new(importer_params)

    respond_to do |format|
      if @importer.save

        @importer.create_contacts
        format.html { redirect_to @importer, notice: "Importer was successfully created." }
        format.json { render :show, status: :created, location: @importer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @importer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /importers/1 or /importers/1.json
  def update
    respond_to do |format|
      if @importer.update(importer_params)
        format.html { redirect_to @importer, notice: "Importer was successfully updated." }
        format.json { render :show, status: :ok, location: @importer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @importer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /importers/1 or /importers/1.json
  def destroy
    @importer.destroy
    respond_to do |format|
      format.html { redirect_to importers_url, notice: "Importer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_importer
      @importer = Importer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def importer_params
      params.require(:importer).permit(files: [])
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :credit_card %>
    <%= form.text_field :credit_card %>
  </div>

  <div class="field">
    <%= form.label :franchise %>
    <%= form.text_field :franchise %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Credit card</th>
      <th>Franchise</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.date_of_birth %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.credit_card %></td>
        <td><%= contact.franchise %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @contact.date_of_birth %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Credit card:</strong>
  <%= @contact.credit_card %>
</p>

<p>
  <strong>Franchise:</strong>
  <%= @contact.franchise %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/importers/_form.html.erb
<%= form_with(model: importer) do |form| %>
  <% if importer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(importer.errors.count, "error") %> prohibited this importer from being saved:</h2>

      <ul>
        <% importer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :files %>
    <%= form.file_field :files, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/importers/edit.html.erb
<h1>Editing Importer</h1>

<%= render 'form', importer: @importer %>

<%= link_to 'Show', @importer %> |
<%= link_to 'Back', importers_path %>

app/views/importers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Importers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @importers.each do |importer| %>
      <tr>
        <td><%= link_to 'Show', importer %></td>
        <td><%= link_to 'Edit', edit_importer_path(importer) %></td>
        <td><%= link_to 'Destroy', importer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Importer', new_importer_path %>

app/views/importers/new.html.erb
<h1>New Importer</h1>

<%= render 'form', importer: @importer %>

<%= link_to 'Back', importers_path %>

app/views/importers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_importer_path(@importer) %> |
<%= link_to 'Back', importers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact Importer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>